array_1 = list(map(int, input().split()))
array_2 = list(map(int, input().split()))
#print(array_1 + array_2)
set_1 = set(array_1)
set_2 = set(array_2)
#print(set(array_1 + array_2))
print('Уникальные элементы 1-ого списка: ', set_1)
print('Уникальные элементы 2-ого списка: ', set_2)
print('Уникальные элементы для объединения этих списков:', set_1 | set_2)
print('Элементы содержащиеся в обоих списках:', set_1 & set_2)
